on: [push]

jobs:
  sync-with-gh-page:
    runs-on: ubuntu-latest
    name: Sync this repo with GH pages
    steps:
    - uses: actions/checkout@v2
      with:
        path: source-repo
    - uses: actions/checkout@v2
      with:
        repository: pawunlu/pawunlu.github.io
        path: target-repo
        token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: Sync the repo
      id: sync
      uses:  tomasdelvechio/actions-push-repo-to-subdir@v1.0.13
      with:
        github-username: 'tomasdelvechio'
        target-subdir-name: 'slides'
        #target-repository: 'pawunlu/pawunlu.github.io'
        #target-repo-subdir-name: 'slides'
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Use the output from the `hello` step
    #- name: Get the output time
    #  run: echo "The time was ${{ steps.hello.outputs.time }}"